name: deal.II v9.3.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: dealii/dealii:v9.3.0-focal
      options: --user root
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: configure
      run: cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX=install
    - name: build
      run: cmake --build build
    - name: install 
      run: cmake --install build
    - name: configure step-1
      run: cmake -Sinstall/examples/step-1 -Bbuild-step-1
    - name: build step-1
      run: cmake --build build-step-1
