name: Documentation
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    
permissions:
  contents: read

jobs:
  build-doc:
    permissions:
      contents: write  # for peaceiris/actions-gh-pages to push pages branch
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13' 

    - name: Install requirements
      run: sudo apt-get install cmake doxygen graphviz -y
      shell: bash
   
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DDOCUMENTATION_ONLY=ON

    - name: Build Documentation
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --target sphinx

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/doc/sphinx/_build/html
        destination_dir: dev

