name: indent

on: pull_request

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  indent:
    name: indent
    runs-on: [ubuntu-24.04]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: install_dependencies
      run: sudo apt update && sudo apt install clang-format-17
    - name: configure
      run: cmake -D DOCUMENTATION_ONLY=ON -S. -Bbuild
    - name: check-format
      run: cmake --build build --target check-format
