name: indent

on: pull_request

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  indent:
    name: indent
    runs-on: [ubuntu-24.04]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: install_dependencies
      run: sudo apt update && sudo apt install clang-format-17
    - name: configure
      run: cmake -D DOCUMENTATION_ONLY=ON -S. -Bbuild
    - name: check-format
      run: cmake --build build --target check-format
