name: indent

on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  indent:
    name: indent
    runs-on: [ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
    
    - name: install_dependencies
      sudo apt update && sudo apt install clang-format
    - name: configure
      cmake -D DOCUMENTATION_ONLY=ON -S. -Bbuild
    - name: check-format
      cmake --build build --target check-format
